### ISSUE TITLE
Refactor css organisation

### ISSUE THREAD

**Issue by Emimint** [Emimint/Allo_Deneigement#53]
# Goals: 
- prevent css leaking
- prevent rules clashes when using Bootstrap:

![image](https://github.com/Emimint/Allo_Deneigement/assets/90863470/fe67e9e3-11f6-4453-b325-782f14a1abd4)

# To-do : 
- [ ] make a separate css file for each page
- [ ] create reusable css variables for text color, background, padding
- [ ] whenever possible, emply relative units (%, rem, vh, ect...)
- [ ] mimick BEM methodology whenever possible (As explained [here](https://bootcamp.uxdesign.cc/introduction-to-bem-block-element-modifier-a-beginners-guide-35e267b6c39e))
